const fs = require('fs');
const path = require('path');
const site = 'C:/Users/claud/OneDrive/Desktop/funparks-website';
const write = (p, c) => { fs.mkdirSync(path.dirname(p),{recursive:true}); fs.writeFileSync(p,c,'utf8'); console.log('wrote:',p.replace(site,'')); };

write(site+'/app/globals.css', `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n* { box-sizing: border-box; padding: 0; margin: 0; }\nhtml { scroll-behavior: smooth; }\nbody { background-color: #0A0A0F; color: #ffffff; font-family: 'Plus Jakarta Sans', sans-serif; -webkit-font-smoothing: antialiased; overflow-x: hidden; }\n::-webkit-scrollbar { width: 6px; }\n::-webkit-scrollbar-track { background: #0A0A0F; }\n::-webkit-scrollbar-thumb { background: #FF6B2B; border-radius: 3px; }\n::selection { background: rgba(255,107,43,0.3); color: white; }\n.glow-orange { box-shadow: 0 0 30px rgba(255,107,43,0.3), 0 0 60px rgba(255,107,43,0.1); }\n.gradient-text { background: linear-gradient(135deg, #FF6B2B 0%, #FF9A5C 50%, #00D4C8 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }\n.glass-card { background: rgba(19,19,26,0.8); backdrop-filter: blur(12px); border: 1px solid rgba(255,255,255,0.06); }\n@keyframes float { 0%,100% { transform: translateY(0px); } 50% { transform: translateY(-12px); } }\n@keyframes glowPulse { 0%,100% { opacity: 0.6; } 50% { opacity: 1; } }\n.animate-float { animation: float 6s ease-in-out infinite; }\n.animate-glow-pulse { animation: glowPulse 3s ease-in-out infinite; }\n`);

write(site+'/app/layout.js', `import './globals.css';\nimport Navbar from '@/components/Navbar';\nimport Footer from '@/components/Footer';\nexport const metadata = { title: "Funparks — The World's Theme Parks in Your Pocket", description: 'Discover 57+ theme parks worldwide.' };\nexport default function RootLayout({ children }) {\n  return (\n    <html lang="en">\n      <head>\n        <link rel="preconnect" href="https://fonts.googleapis.com" />\n        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />\n        <link href="https://fonts.googleapis.com/css2?family=Syne:wght@400;500;600;700;800&family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet" />\n      </head>\n      <body><Navbar /><main>{children}</main><Footer /></body>\n    </html>\n  );\n}\n`);

write(site+'/app/page.js', `import Hero from '@/components/Hero';\nimport Stats from '@/components/Stats';\nimport Features from '@/components/Features';\nimport ParksShowcase from '@/components/ParksShowcase';\nimport SocialStrip from '@/components/SocialStrip';\nimport DownloadSection from '@/components/DownloadSection';\nexport default function HomePage() {\n  return (<><Hero /><Stats /><Features /><ParksShowcase /><SocialStrip /><DownloadSection /></>);\n}\n`);

console.log('Core app files done');