const fs = require('fs');
const path = require('path');
const site = 'C:/Users/claud/OneDrive/Desktop/funparks-website';
const write = (p, c) => {
  fs.mkdirSync(path.dirname(p), {recursive:true});
  fs.writeFileSync(p, c, 'utf8');
  console.log('wrote:', p.replace(site,''));
};

// GLOBALS CSS
write(site+'/app/globals.css', [
'@tailwind base;',
'@tailwind components;',
'@tailwind utilities;',
'',
'* { box-sizing: border-box; padding: 0; margin: 0; }',
'html { scroll-behavior: smooth; }',
'body { background: #f8f7ff; color: #1a1a2e; font-family: "Plus Jakarta Sans", sans-serif; -webkit-font-smoothing: antialiased; overflow-x: hidden; }',
'::-webkit-scrollbar { width: 6px; }',
'::-webkit-scrollbar-track { background: #f0f0ff; }',
'::-webkit-scrollbar-thumb { background: linear-gradient(#FF6B2B, #a855f7); border-radius: 3px; }',
'::selection { background: rgba(168,85,247,0.2); color: #1a1a2e; }',
'.gradient-text { background: linear-gradient(135deg, #FF6B2B 0%, #f43f5e 40%, #a855f7 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }',
'.gradient-text-2 { background: linear-gradient(135deg, #a855f7 0%, #06b6d4 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }',
'.glass-card { background: rgba(255,255,255,0.7); backdrop-filter: blur(16px); border: 1px solid rgba(255,255,255,0.9); box-shadow: 0 4px 24px rgba(168,85,247,0.08), 0 1px 4px rgba(0,0,0,0.04); }',
'.glow-orange { box-shadow: 0 0 30px rgba(255,107,43,0.4), 0 4px 12px rgba(255,107,43,0.2); }',
'.btn-gradient { background: linear-gradient(135deg, #FF6B2B, #f43f5e, #a855f7); background-size: 200% 200%; transition: all 0.3s ease; }',
'.btn-gradient:hover { transform: translateY(-1px); }',
'@keyframes blob1 { 0%,100%{transform:translate(0,0) scale(1)} 33%{transform:translate(30px,-20px) scale(1.05)} 66%{transform:translate(-20px,10px) scale(0.97)} }',
'@keyframes blob2 { 0%,100%{transform:translate(0,0) scale(1)} 33%{transform:translate(-25px,15px) scale(1.03)} 66%{transform:translate(20px,-10px) scale(0.98)} }',
'@keyframes float { 0%,100%{transform:translateY(0)} 50%{transform:translateY(-12px)} }',
'@keyframes glowPulse { 0%,100%{opacity:0.6} 50%{opacity:1} }',
'.animate-blob1 { animation: blob1 8s ease-in-out infinite; }',
'.animate-blob2 { animation: blob2 10s ease-in-out infinite; }',
'.animate-float { animation: float 6s ease-in-out infinite; }',
'.animate-glow-pulse { animation: glowPulse 3s ease-in-out infinite; }',
].join('\n'));

// TAILWIND CONFIG
write(site+'/tailwind.config.js', [
"module.exports = {",
"  content: ['./pages/**/*.{js,jsx}','./components/**/*.{js,jsx}','./app/**/*.{js,jsx}'],",
"  theme: { extend: { colors: { brand: { orange:'#FF6B2B', purple:'#a855f7', teal:'#06b6d4', pink:'#f43f5e', bg:'#f8f7ff' } }, fontFamily: { display: ['Syne','sans-serif'], body: ['Plus Jakarta Sans','sans-serif'] } } },",
"  plugins: [],",
"};",
].join('\n'));

// NAVBAR
write(site+'/components/Navbar.js', [
"'use client';",
"import { useState, useEffect } from 'react';",
"import Link from 'next/link';",
"export default function Navbar() {",
"  const [scrolled, setScrolled] = useState(false);",
"  const [open, setOpen] = useState(false);",
"  useEffect(() => {",
"    const fn = () => setScrolled(window.scrollY > 20);",
"    window.addEventListener('scroll', fn);",
"    return () => window.removeEventListener('scroll', fn);",
"  }, []);",
"  const links = [{label:'Parks',href:'/parks'},{label:'Features',href:'/#features'},{label:'Blog',href:'/blog'},{label:'About',href:'/about'},{label:'Contact',href:'/contact'}];",
"  const scrolledClass = 'bg-white/80 backdrop-blur-xl shadow-sm border-b border-purple-100 py-3';",
"  const normalClass = 'bg-transparent py-5';",
"  return (",
"    <header className={'fixed top-0 left-0 right-0 z-50 transition-all duration-300 ' + (scrolled ? scrolledClass : normalClass)}>",
"      <div className='max-w-7xl mx-auto px-6 flex items-center justify-between'>",
"        <Link href='/' className='flex items-center gap-2'>",
"          <div className='w-9 h-9 rounded-xl btn-gradient flex items-center justify-center glow-orange'>",
"            <span className='text-white font-black text-base' style={{fontFamily:'Syne,sans-serif'}}>F</span>",
"          </div>",
"          <span className='font-black text-xl text-gray-900' style={{fontFamily:'Syne,sans-serif'}}>fun<span className='gradient-text'>parks</span></span>",
"        </Link>",
"        <nav className='hidden md:flex items-center gap-8'>",
"          {links.map(l => <Link key={l.href} href={l.href} className='text-sm text-gray-500 hover:text-gray-900 transition-colors font-semibold'>{l.label}</Link>)}",
"        </nav>",
"        <Link href='/#download' className='hidden md:flex px-5 py-2.5 rounded-xl btn-gradient text-white text-sm font-bold shadow-lg hover:shadow-xl transition-all'>Download Free</Link>",
"        <button className='md:hidden text-gray-600 hover:text-gray-900' onClick={() => setOpen(!open)}>",
"          <svg className='w-6 h-6' fill='none' stroke='currentColor' viewBox='0 0 24 24'>",
"            <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2} d={open ? 'M6 18L18 6M6 6l12 12' : 'M4 6h16M4 12h16M4 18h16'} />",
"          </svg>",
"        </button>",
"      </div>",
"      {open && (",
"        <div className='md:hidden bg-white/95 backdrop-blur-xl border-t border-gray-100 px-6 py-6 flex flex-col gap-5'>",
"          {links.map(l => <Link key={l.href} href={l.href} onClick={() => setOpen(false)} className='text-gray-700 hover:text-gray-900 text-base font-semibold'>{l.label}</Link>)}",
"          <Link href='/#download' onClick={() => setOpen(false)} className='mt-2 px-5 py-3 rounded-xl btn-gradient text-white text-sm font-bold text-center'>Download Free</Link>",
"        </div>",
"      )}",
"    </header>",
"  );",
"}",
].join('\n'));

// STATS
write(site+'/components/Stats.js', [
"export default function Stats() {",
"  const s=[",
"    {v:'57+',l:'Theme Parks',sub:'Across 6 continents',emoji:'🌍',color:'#FF6B2B'},",
"    {v:'1,000+',l:'Attractions',sub:'With live wait times',emoji:'🎢',color:'#f43f5e'},",
"    {v:'10',l:'Languages',sub:'Fully translated',emoji:'🌐',color:'#a855f7'},",
"    {v:'AI',l:'Park Assistant',sub:'Built-in smart guide',emoji:'🤖',color:'#06b6d4'},",
"  ];",
"  return (",
"    <section className='py-16 relative overflow-hidden' style={{background:'linear-gradient(135deg,#fff7f5,#fdf4ff,#f0fdff)'}}>",
"      <div className='max-w-7xl mx-auto px-6'>",
"        <div className='grid grid-cols-2 lg:grid-cols-4 gap-6'>",
"          {s.map((x,i) => (",
"            <div key={i} className='bg-white rounded-2xl p-6 text-center hover:scale-105 transition-transform duration-300 shadow-sm border-2 border-gray-50'>",
"              <div className='text-3xl mb-2'>{x.emoji}</div>",
"              <p className='text-4xl lg:text-5xl font-black mb-1' style={{fontFamily:'Syne,sans-serif',color:x.color}}>{x.v}</p>",
"              <p className='text-gray-900 font-bold text-sm mb-0.5'>{x.l}</p>",
"              <p className='text-gray-400 text-xs'>{x.sub}</p>",
"            </div>",
"          ))}",
"        </div>",
"      </div>",
"    </section>",
"  );",
"}",
].join('\n'));

// FEATURES
write(site+'/components/Features.js', [
"export default function Features() {",
"  const f=[",
"    {icon:'⚡',title:'Live Wait Times',desc:'See real-time queue times for every attraction before you leave the hotel.',gradient:'from-orange-400 to-red-400'},",
"    {icon:'🤖',title:'AI Park Assistant',desc:'Ask anything — Plan my day at Cedar Point or Best ride for my 8-year-old.',gradient:'from-purple-400 to-blue-400'},",
"    {icon:'🗺️',title:'Interactive Maps',desc:'Explore every park on an interactive map. Find attractions, food and your group.',gradient:'from-teal-400 to-cyan-400'},",
"    {icon:'🍔',title:'Food & Dining Guides',desc:'Curated restaurant reviews for every park with menus, prices and recommendations.',gradient:'from-pink-400 to-rose-400'},",
"    {icon:'🏨',title:'On-Site Hotels',desc:'The best hotels near every park with reviews, prices and direct booking links.',gradient:'from-violet-400 to-purple-400'},",
"    {icon:'🌍',title:'Global Coverage',desc:'From Walt Disney World to Tokyo DisneySea to Parque de la Costa — 57 parks, 6 continents.',gradient:'from-emerald-400 to-teal-400'},",
"  ];",
"  return (",
"    <section id='features' className='py-24 bg-white'>",
"      <div className='max-w-7xl mx-auto px-6'>",
"        <div className='text-center mb-16'>",
"          <div className='inline-flex items-center gap-2 px-4 py-2 rounded-full bg-purple-50 text-purple-600 text-sm font-bold mb-4'>✨ Features</div>",
"          <h2 className='text-4xl lg:text-5xl font-black text-gray-900 mb-4' style={{fontFamily:'Syne,sans-serif'}}>Everything for<br /><span className='gradient-text'>the perfect park day</span></h2>",
"          <p className='text-gray-500 text-lg max-w-xl mx-auto'>Every feature a theme park enthusiast could dream of.</p>",
"        </div>",
"        <div className='grid md:grid-cols-2 lg:grid-cols-3 gap-6'>",
"          {f.map((x,i) => (",
"            <div key={i} className={'group rounded-3xl p-6 border-2 border-gray-100 bg-white hover:border-purple-200 hover:shadow-xl hover:shadow-purple-50 transition-all duration-300 hover:-translate-y-1'}>",
"              <div className={'w-14 h-14 rounded-2xl bg-gradient-to-br ' + x.gradient + ' flex items-center justify-center text-2xl mb-5 shadow-lg group-hover:scale-110 transition-transform'}>{x.icon}</div>",
"              <h3 className='text-gray-900 font-black text-lg mb-2' style={{fontFamily:'Syne,sans-serif'}}>{x.title}</h3>",
"              <p className='text-gray-500 text-sm leading-relaxed'>{x.desc}</p>",
"            </div>",
"          ))}",
"        </div>",
"      </div>",
"    </section>",
"  );",
"}",
].join('\n'));

// PARKS SHOWCASE
write(site+'/components/ParksShowcase.js', [
"import Link from 'next/link';",
"const parks=[",
"  {name:'Magic Kingdom',location:'Orlando, USA',emoji:'🏰',tag:'Disney',color:'#FF6B2B'},",
"  {name:'Tokyo DisneySea',location:'Tokyo, Japan',emoji:'⛵',tag:'Disney',color:'#f43f5e'},",
"  {name:'Cedar Point',location:'Sandusky, USA',emoji:'🎢',tag:'Thrill',color:'#a855f7'},",
"  {name:'Alton Towers',location:'Staffordshire, UK',emoji:'🏰',tag:'Merlin',color:'#06b6d4'},",
"  {name:'Universal Studios FL',location:'Orlando, USA',emoji:'🎬',tag:'Universal',color:'#FF6B2B'},",
"  {name:'Six Flags Magic Mtn.',location:'Valencia, USA',emoji:'⚡',tag:'Six Flags',color:'#f43f5e'},",
"  {name:'Ferrari World',location:'Abu Dhabi, UAE',emoji:'🏎️',tag:'Unique',color:'#a855f7'},",
"  {name:'Parque de la Costa',location:'Tigre, Argentina',emoji:'🌊',tag:'South America',color:'#06b6d4'},",
"];",
"export default function ParksShowcase() {",
"  return (",
"    <section className='py-24 relative overflow-hidden' style={{background:'linear-gradient(135deg,#fdf4ff,#f0fdff,#fff7f5)'}}>",
"      <div className='max-w-7xl mx-auto px-6 relative'>",
"        <div className='flex flex-col md:flex-row items-start md:items-end justify-between gap-6 mb-12'>",
"          <div>",
"            <div className='inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white shadow-sm border border-purple-100 text-purple-600 text-sm font-bold mb-4'>🌍 Parks</div>",
"            <h2 className='text-4xl lg:text-5xl font-black text-gray-900' style={{fontFamily:'Syne,sans-serif'}}>57 parks,<br /><span className='gradient-text-2'>6 continents</span></h2>",
"          </div>",
"          <Link href='/parks' className='inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-white shadow-md border border-purple-100 text-gray-700 font-bold hover:shadow-lg transition-all'>View all parks →</Link>",
"        </div>",
"        <div className='grid sm:grid-cols-2 lg:grid-cols-4 gap-4'>",
"          {parks.map((p,i) => (",
"            <Link key={i} href='/parks' className='group bg-white rounded-2xl p-5 border-2 border-gray-100 hover:border-purple-200 hover:shadow-xl hover:shadow-purple-50 transition-all duration-300 hover:-translate-y-1 cursor-pointer'>",
"              <div className='flex items-start justify-between mb-4'>",
"                <div className='w-12 h-12 rounded-xl flex items-center justify-center text-2xl shadow-sm' style={{backgroundColor:p.color+'15'}}>{p.emoji}</div>",
"                <span className='text-xs font-bold px-2 py-1 rounded-full' style={{backgroundColor:p.color+'15',color:p.color}}>{p.tag}</span>",
"              </div>",
"              <h3 className='text-gray-900 font-black text-sm mb-1 group-hover:text-purple-600 transition-colors' style={{fontFamily:'Syne,sans-serif'}}>{p.name}</h3>",
"              <p className='text-gray-400 text-xs font-medium'>{p.location}</p>",
"            </Link>",
"          ))}",
"        </div>",
"      </div>",
"    </section>",
"  );",
"}",
].join('\n'));

// SOCIAL STRIP
const igSvg = '<svg viewBox="0 0 24 24" fill="currentColor" className="w-6 h-6"><path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/></svg>';
const ttSvg = '<svg viewBox="0 0 24 24" fill="currentColor" className="w-6 h-6"><path d="M19.59 6.69a4.83 4.83 0 01-3.77-4.25V2h-3.45v13.67a2.89 2.89 0 01-2.88 2.5 2.89 2.89 0 01-2.89-2.89 2.89 2.89 0 012.89-2.89c.28 0 .54.04.79.1V9.01a6.33 6.33 0 00-.79-.05 6.34 6.34 0 00-6.34 6.34 6.34 6.34 0 006.34 6.34 6.34 6.34 0 006.33-6.34V8.67a8.18 8.18 0 004.77 1.52V6.74a4.85 4.85 0 01-1-.05z"/></svg>';
const ytSvg = '<svg viewBox="0 0 24 24" fill="currentColor" className="w-6 h-6"><path d="M23.498 6.186a3.016 3.016 0 00-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 00.502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 002.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 002.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/></svg>';
const fbSvg = '<svg viewBox="0 0 24 24" fill="currentColor" className="w-6 h-6"><path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/></svg>';

write(site+'/components/SocialStrip.js', [
"const IG=()=><span dangerouslySetInnerHTML={{__html:'"+igSvg.replace(/'/g,"\\'")+"'}} />;",
"const TT=()=><span dangerouslySetInnerHTML={{__html:'"+ttSvg.replace(/'/g,"\\'")+"'}} />;",
"const YT=()=><span dangerouslySetInnerHTML={{__html:'"+ytSvg.replace(/'/g,"\\'")+"'}} />;",
"const FB=()=><span dangerouslySetInnerHTML={{__html:'"+fbSvg.replace(/'/g,"\\'")+"'}} />;",
"export default function SocialStrip() {",
"  const s=[",
"    {icon:<IG/>,name:'Instagram',handle:'@funparksworld',desc:'Park photos & reels',href:'https://www.instagram.com/funparksworld/',color:'#E1306C',bg:'linear-gradient(135deg,#f09433,#dc2743,#bc1888)'},",
"    {icon:<TT/>,name:'TikTok',handle:'@funparks',desc:'Ride POVs & tips',href:'https://www.tiktok.com/@funparks',color:'#010101',bg:'linear-gradient(135deg,#010101,#69C9D0)'},",
"    {icon:<YT/>,name:'YouTube',handle:'@Funparks-u7k',desc:'Park guides & reviews',href:'https://www.youtube.com/@Funparks-u7k',color:'#FF0000',bg:'linear-gradient(135deg,#FF0000,#cc0000)'},",
"    {icon:<FB/>,name:'Facebook',handle:'Funparks',desc:'Community & updates',href:'https://www.facebook.com/share/17T2h2NwmT/',color:'#1877F2',bg:'linear-gradient(135deg,#1877F2,#0d5bba)'},",
"  ];",
"  return (",
"    <section className='py-24 bg-white'>",
"      <div className='max-w-7xl mx-auto px-6'>",
"        <div className='text-center mb-12'>",
"          <div className='inline-flex items-center gap-2 px-4 py-2 rounded-full bg-pink-50 text-pink-600 text-sm font-bold mb-4'>❤️ Community</div>",
"          <h2 className='text-4xl lg:text-5xl font-black text-gray-900' style={{fontFamily:'Syne,sans-serif'}}>Follow the <span className='gradient-text'>adventure</span></h2>",
"          <p className='text-gray-500 text-base mt-4 max-w-md mx-auto'>Park content, tips, ride POVs and app updates every week.</p>",
"        </div>",
"        <div className='grid sm:grid-cols-2 lg:grid-cols-4 gap-5'>",
"          {s.map(x => (",
"            <a key={x.name} href={x.href} target='_blank' rel='noopener noreferrer'",
"              className='group rounded-3xl p-6 flex flex-col items-center text-center border-2 border-gray-100 bg-white hover:border-transparent hover:shadow-2xl transition-all duration-300 hover:-translate-y-2'>",
"              <div className='w-16 h-16 rounded-2xl flex items-center justify-center mb-4 text-white shadow-lg group-hover:scale-110 transition-transform' style={{background:x.bg}}>{x.icon}</div>",
"              <h3 className='text-gray-900 font-black text-base mb-1' style={{fontFamily:'Syne,sans-serif'}}>{x.name}</h3>",
"              <p className='text-gray-400 text-xs font-medium mb-3'>{x.handle}</p>",
"              <span className='text-xs font-bold px-3 py-1.5 rounded-full bg-gray-50 text-gray-600'>{x.desc}</span>",
"            </a>",
"          ))}",
"        </div>",
"      </div>",
"    </section>",
"  );",
"}",
].join('\n'));

// DOWNLOAD SECTION
write(site+'/components/DownloadSection.js', [
"'use client';",
"import { useState } from 'react';",
"const PLAY='https://play.google.com/store/apps/details?id=com.funparks.app';",
"const IOS='https://apps.apple.com/app/funparks/id000000000';",
"function QR({url,label}){",
"  const src='https://api.qrserver.com/v1/create-qr-code/?size=160x160&data='+encodeURIComponent(url)+'&bgcolor=ffffff&color=1a1a2e&margin=10';",
"  return (",
"    <div className='flex flex-col items-center gap-3'>",
"      <div className='p-3 rounded-2xl bg-white border-2 border-purple-100 shadow-lg'>",
"        <img src={src} alt={'QR '+label} width={120} height={120} className='rounded-lg' />",
"      </div>",
"      <p className='text-white/40 text-xs text-center font-medium'>Scan to download<br/>{label}</p>",
"    </div>",
"  );",
"}",
"export default function DownloadSection(){",
"  const [tab,setTab]=useState('android');",
"  return (",
"    <section id='download' className='py-24 relative overflow-hidden' style={{background:'linear-gradient(135deg,#1a1a2e,#2d1b69,#1a1a2e)'}}>",
"      <div className='absolute top-0 left-0 w-96 h-96 rounded-full opacity-20 blur-3xl' style={{background:'radial-gradient(#FF6B2B,transparent)'}} />",
"      <div className='absolute bottom-0 right-0 w-80 h-80 rounded-full opacity-20 blur-3xl' style={{background:'radial-gradient(#a855f7,transparent)'}} />",
"      <div className='max-w-7xl mx-auto px-6 relative'>",
"        <div className='grid lg:grid-cols-2 gap-16 items-center'>",
"          <div>",
"            <div className='inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/10 text-white/70 text-sm font-bold mb-6'>📱 Download</div>",
"            <h2 className='text-4xl lg:text-5xl font-black text-white mb-5 leading-tight' style={{fontFamily:'Syne,sans-serif'}}>Get Funparks.<br/><span className='gradient-text'>It is free.</span></h2>",
"            <p className='text-white/60 text-lg leading-relaxed mb-10 max-w-md'>57 theme parks worldwide. Free forever — no subscription, no paywalls.</p>",
"            <div className='flex flex-col sm:flex-row gap-4 mb-8'>",
"              <a href={PLAY} target='_blank' rel='noopener noreferrer' className='flex items-center gap-4 px-6 py-4 rounded-2xl bg-white text-gray-900 font-bold hover:bg-gray-50 transition-all shadow-xl'>",
"                <div><div className='text-xs text-gray-400 uppercase tracking-wider mb-0.5'>Get it on</div><div className='font-black text-sm'>Google Play 🤖</div></div>",
"              </a>",
"              <a href={IOS} target='_blank' rel='noopener noreferrer' className='flex items-center gap-4 px-6 py-4 rounded-2xl bg-white/10 border border-white/20 text-white hover:bg-white/20 transition-all'>",
"                <div><div className='text-xs text-white/40 uppercase tracking-wider mb-0.5'>Download on the</div><div className='font-black text-sm'>App Store 🍎</div></div>",
"              </a>",
"            </div>",
"            <ul className='space-y-2'>",
"              {['Free forever','57 parks worldwide and growing','AI assistant included','Works on Android and iOS'].map(x => (",
"                <li key={x} className='flex items-center gap-3 text-white/60 text-sm font-medium'>",
"                  <div className='w-5 h-5 rounded-full bg-gradient-to-br from-green-400 to-teal-400 flex items-center justify-center flex-shrink-0 text-white text-xs font-black'>✓</div>{x}",
"                </li>",
"              ))}",
"            </ul>",
"          </div>",
"          <div className='flex flex-col items-center'>",
"            <div className='bg-white/10 backdrop-blur-xl rounded-3xl p-8 border border-white/20 w-full max-w-sm shadow-2xl'>",
"              <h3 className='text-white font-black text-lg text-center mb-2' style={{fontFamily:'Syne,sans-serif'}}>Scan to Download</h3>",
"              <p className='text-white/40 text-sm text-center mb-6 font-medium'>Point your camera at the QR code</p>",
"              <div className='flex rounded-xl bg-white/10 p-1 mb-6'>",
"                {['android','ios'].map(t => (",
"                  <button key={t} onClick={() => setTab(t)} className={'flex-1 py-2.5 rounded-lg text-sm font-bold transition-all ' + (tab===t ? 'btn-gradient text-white shadow-lg' : 'text-white/50 hover:text-white/80')}>",
"                    {t==='android' ? '🤖 Android' : '🍎 iOS'}",
"                  </button>",
"                ))}",
"              </div>",
"              <div className='flex justify-center'>",
"                {tab==='android' ? <QR url={PLAY} label='Google Play'/> : <QR url={IOS} label='App Store'/>}",
"              </div>",
"              <p className='text-white/20 text-xs text-center mt-5 font-medium'>Available on Android 6.0+ and iOS 14+</p>",
"            </div>",
"          </div>",
"        </div>",
"      </div>",
"    </section>",
"  );",
"}",
].join('\n'));

// FOOTER
write(site+'/components/Footer.js', [
"import Link from 'next/link';",
"export default function Footer(){",
"  const socials=[",
"    {icon:'📸',href:'https://www.instagram.com/funparksworld/',label:'Instagram',bg:'linear-gradient(135deg,#f09433,#dc2743,#bc1888)'},",
"    {icon:'🎵',href:'https://www.tiktok.com/@funparks',label:'TikTok',bg:'linear-gradient(135deg,#010101,#69C9D0)'},",
"    {icon:'▶️',href:'https://www.youtube.com/@Funparks-u7k',label:'YouTube',bg:'linear-gradient(135deg,#FF0000,#cc0000)'},",
"    {icon:'👥',href:'https://www.facebook.com/share/17T2h2NwmT/',label:'Facebook',bg:'linear-gradient(135deg,#1877F2,#0d5bba)'},",
"  ];",
"  const nav=[{label:'Home',href:'/'},{label:'Parks',href:'/parks'},{label:'Blog',href:'/blog'},{label:'About',href:'/about'},{label:'Contact',href:'/contact'}];",
"  return (",
"    <footer style={{background:'linear-gradient(135deg,#1a1a2e,#2d1b69)'}}>",
"      <div className='max-w-7xl mx-auto px-6 py-16'>",
"        <div className='grid grid-cols-1 md:grid-cols-4 gap-12'>",
"          <div className='md:col-span-2'>",
"            <div className='flex items-center gap-2 mb-4'>",
"              <div className='w-10 h-10 rounded-xl btn-gradient flex items-center justify-center shadow-lg'>",
"                <span className='text-white font-black text-lg' style={{fontFamily:'Syne,sans-serif'}}>F</span>",
"              </div>",
"              <span className='font-black text-xl text-white' style={{fontFamily:'Syne,sans-serif'}}>fun<span className='gradient-text'>parks</span></span>",
"            </div>",
"            <p className='text-white/50 text-sm leading-relaxed max-w-xs mb-6 font-medium'>The world's theme parks in your pocket. 57+ parks across 6 continents — free forever.</p>",
"            <div className='flex items-center gap-3'>",
"              {socials.map(s => (",
"                <a key={s.label} href={s.href} target='_blank' rel='noopener noreferrer' aria-label={s.label}",
"                  className='w-9 h-9 rounded-xl flex items-center justify-center text-base hover:scale-110 transition-transform shadow-lg'",
"                  style={{background:s.bg}}>",
"                  {s.icon}",
"                </a>",
"              ))}",
"            </div>",
"          </div>",
"          <div>",
"            <h4 className='text-white font-black text-sm mb-5 uppercase tracking-wider' style={{fontFamily:'Syne,sans-serif'}}>Navigation</h4>",
"            <ul className='space-y-3'>{nav.map(l => <li key={l.href}><Link href={l.href} className='text-white/50 hover:text-white text-sm font-medium transition-colors'>{l.label}</Link></li>)}</ul>",
"          </div>",
"          <div>",
"            <h4 className='text-white font-black text-sm mb-5 uppercase tracking-wider' style={{fontFamily:'Syne,sans-serif'}}>Get the App</h4>",
"            <div className='flex flex-col gap-3'>",
"              <a href='https://play.google.com/store/apps/details?id=com.funparks.app' target='_blank' rel='noopener noreferrer' className='flex items-center gap-3 px-4 py-3 rounded-xl bg-white/10 hover:bg-white/20 border border-white/10 transition-all'>",
"                <div><div className='text-xs text-white/40 uppercase tracking-wider'>Get it on</div><div className='text-white text-sm font-bold'>Google Play 🤖</div></div>",
"              </a>",
"              <a href='#' className='flex items-center gap-3 px-4 py-3 rounded-xl bg-white/10 hover:bg-white/20 border border-white/10 transition-all'>",
"                <div><div className='text-xs text-white/40 uppercase tracking-wider'>Download on the</div><div className='text-white text-sm font-bold'>App Store 🍎</div></div>",
"              </a>",
"            </div>",
"          </div>",
"        </div>",
"        <div className='mt-14 pt-6 border-t border-white/10 flex flex-col md:flex-row items-center justify-between gap-4'>",
"          <p className='text-white/30 text-xs font-medium'>© 2026 Funparks. All rights reserved.</p>",
"          <div className='flex items-center gap-6'>",
"            <Link href='/privacy' className='text-white/30 hover:text-white/60 text-xs font-medium'>Privacy Policy</Link>",
"            <Link href='/terms' className='text-white/30 hover:text-white/60 text-xs font-medium'>Terms of Service</Link>",
"          </div>",
"        </div>",
"      </div>",
"    </footer>",
"  );",
"}",
].join('\n'));

// HERO - simple version without complex template literals
write(site+'/components/Hero.js', [
"'use client';",
"import Link from 'next/link';",
"export default function Hero() {",
"  const parks = [",
"    {name:'Magic Kingdom',flag:'🇺🇸',wait:'45 min',color:'#FF6B2B'},",
"    {name:'Tokyo DisneySea',flag:'🇯🇵',wait:'68 min',color:'#a855f7'},",
"    {name:'Cedar Point',flag:'🇺🇸',wait:'32 min',color:'#06b6d4'},",
"  ];",
"  return (",
"    <section className='relative min-h-screen flex items-center justify-center overflow-hidden pt-20'>",
"      <div className='absolute inset-0 pointer-events-none overflow-hidden'>",
"        <div className='absolute -top-40 -left-40 w-96 h-96 rounded-full opacity-30 animate-blob1' style={{background:'radial-gradient(circle, #FF6B2B, #f43f5e, transparent)'}} />",
"        <div className='absolute -bottom-40 -right-40 w-80 h-80 rounded-full opacity-25 animate-blob2' style={{background:'radial-gradient(circle, #a855f7, #06b6d4, transparent)'}} />",
"      </div>",
"      <div className='absolute inset-0 opacity-5' style={{backgroundImage:'radial-gradient(#a855f7 1px, transparent 1px)',backgroundSize:'32px 32px'}} />",
"      <div className='relative max-w-7xl mx-auto px-6 py-20 grid lg:grid-cols-2 gap-16 items-center'>",
"        <div>",
"          <div className='inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white shadow-md border border-purple-100 text-sm font-semibold text-purple-600 mb-8'>",
"            <span className='w-2 h-2 rounded-full bg-green-500 animate-pulse' />",
"            57 parks across 6 continents",
"          </div>",
"          <h1 className='text-5xl lg:text-7xl font-black leading-none mb-6 tracking-tight text-gray-900' style={{fontFamily:'Syne,sans-serif'}}>",
"            Every<br /><span className='gradient-text'>Theme Park.</span><br />One App.",
"          </h1>",
"          <p className='text-gray-500 text-lg leading-relaxed max-w-md mb-10'>",
"            Real-time wait times, AI park assistant, curated food and hotel guides. Everything for the perfect theme park day.",
"          </p>",
"          <div className='flex flex-col sm:flex-row gap-4 mb-10'>",
"            <Link href='/#download' className='inline-flex items-center justify-center gap-2 px-7 py-4 rounded-2xl btn-gradient text-white font-bold text-base shadow-xl'>",
"              Download Free 🎢",
"            </Link>",
"            <Link href='/parks' className='inline-flex items-center justify-center gap-2 px-7 py-4 rounded-2xl bg-white border-2 border-purple-200 text-gray-700 font-bold text-base hover:border-purple-400 transition-all shadow-md'>",
"              Explore Parks 🗺️",
"            </Link>",
"          </div>",
"          <p className='text-gray-400 text-sm font-medium'>Free forever · Android and iOS · No subscription</p>",
"        </div>",
"        <div className='relative flex items-center justify-center'>",
"          <div className='absolute w-72 h-72 rounded-full opacity-20 animate-blob2' style={{background:'radial-gradient(circle,#a855f7,#06b6d4,transparent)'}} />",
"          <div className='relative animate-float w-64 lg:w-72 rounded-3xl overflow-hidden flex flex-col shadow-2xl border-4 border-white' style={{aspectRatio:'9/19',background:'white',boxShadow:'0 40px 80px rgba(168,85,247,0.25)'}}>",
"            <div className='h-8 flex items-center justify-between px-5' style={{background:'linear-gradient(135deg,#FF6B2B,#f43f5e,#a855f7)'}}>",
"              <span className='text-white text-xs font-bold'>9:41</span>",
"              <div className='w-14 h-3 rounded-full bg-black/30' />",
"              <span className='text-white text-xs'>●●●</span>",
"            </div>",
"            <div className='px-5 pt-4 pb-2 bg-white'>",
"              <p className='text-gray-400 text-xs uppercase tracking-widest font-bold'>Discover</p>",
"              <p className='text-gray-900 font-black text-lg' style={{fontFamily:'Syne,sans-serif'}}>Parks 🎡</p>",
"              <div className='mt-2 h-8 rounded-xl bg-purple-50 border border-purple-100 flex items-center px-3 gap-2'>",
"                <div className='w-3 h-3 rounded-full border-2 border-purple-300' />",
"                <div className='h-2 w-24 rounded-full bg-purple-100' />",
"              </div>",
"            </div>",
"            <div className='mx-4 mb-3 h-24 rounded-2xl overflow-hidden relative border-2 border-purple-50' style={{background:'linear-gradient(135deg,#fdf4ff,#eff6ff)'}}>",
"              <div className='absolute inset-0 opacity-30' style={{backgroundImage:'linear-gradient(rgba(168,85,247,0.2) 1px,transparent 1px),linear-gradient(90deg,rgba(168,85,247,0.2) 1px,transparent 1px)',backgroundSize:'16px 16px'}} />",
"              {[{t:'30%',l:'25%',c:'#FF6B2B'},{t:'50%',l:'55%',c:'#a855f7'},{t:'65%',l:'35%',c:'#f43f5e'},{t:'20%',l:'70%',c:'#06b6d4'}].map((d,i) => (",
"                <div key={i} className='absolute w-4 h-4 rounded-full border-2 border-white shadow-md' style={{top:d.t,left:d.l,backgroundColor:d.c}} />",
"              ))}",
"            </div>",
"            <div className='px-4 flex-1 space-y-2 overflow-hidden'>",
"              {parks.map(p => (",
"                <div key={p.name} className='flex items-center gap-3 p-2 rounded-xl bg-gray-50 border border-gray-100'>",
"                  <div className='w-8 h-8 rounded-lg flex items-center justify-center text-base flex-shrink-0' style={{backgroundColor:p.color+'15'}}>{p.flag}</div>",
"                  <div className='flex-1 min-w-0'>",
"                    <p className='text-gray-900 text-xs font-bold truncate'>{p.name}</p>",
"                    <p className='text-gray-400 text-xs'>Avg wait: {p.wait}</p>",
"                  </div>",
"                  <div className='w-2 h-2 rounded-full flex-shrink-0' style={{backgroundColor:p.color}} />",
"                </div>",
"              ))}",
"            </div>",
"            <div className='flex items-center justify-around px-5 py-3 mt-2 border-t border-gray-100 bg-white'>",
"              <span className='text-sm' style={{filter:'drop-shadow(0 0 4px #FF6B2B)'}}>⊞</span>",
"              <span className='text-sm opacity-30'>🗺</span>",
"              <span className='text-sm opacity-30'>★</span>",
"              <span className='text-sm opacity-30'>👤</span>",
"            </div>",
"          </div>",
"          <div className='absolute -right-4 top-1/4 bg-white rounded-2xl px-3 py-2 shadow-xl border border-purple-100'>",
"            <p className='text-xs text-gray-400 font-medium'>Wait time</p>",
"            <p className='font-black text-sm' style={{color:'#06b6d4'}}>12 min ⚡</p>",
"          </div>",
"          <div className='absolute -left-8 bottom-1/3 bg-white rounded-2xl px-3 py-2 shadow-xl border border-orange-100'>",
"            <p className='text-xs text-gray-400 font-medium'>Parks nearby</p>",
"            <p className='font-black text-sm' style={{color:'#FF6B2B'}}>3 parks 🎢</p>",
"          </div>",
"        </div>",
"      </div>",
"    </section>",
"  );",
"}",
].join('\n'));

console.log('\n✅ All components written successfully!');
